export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'

export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'

export const LOGOUT_USER = 'LOGOUT_USER'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'

export const CLEAR_VALUES = 'CLEAR_VALUES'

export const CREATE_STAFF_BEGIN = 'CREATE_STAFF_BEGIN'
export const CREATE_STAFF_SUCCESS = 'CREATE_STAFF_SUCCESS'
export const CREATE_STAFF_ERROR = 'CREATE_STAFF_ERROR'

export const GET_STAFFS_BEGIN = 'GET_STAFFS_BEGIN'
export const GET_STAFFS_SUCCESS = 'GET_STAFFS_SUCCESS'

export const SET_EDIT_STAFF = 'SET_EDIT_STAFF'

export const EDIT_STAFF_BEGIN = 'EDIT_STAFF_BEGIN'
export const EDIT_STAFF_SUCCESS = 'EDIT_STAFF_SUCCESS'
export const EDIT_STAFF_ERROR = 'EDIT_STAFF_ERROR'

export const DELETE_STAFF = 'DELETE_STAFF'
